version: '3.8'

services:
  main-app:
    #  restart: always
    image: b0pof/bizon-main
    environment:
      - CONFIG_PATH=./config/prod.yaml
    ports:
      - '8080:8080'
    healthcheck:
      test: ["CMD", "bash", "-c", "echo -n '' > /dev/tcp/127.0.0.1/8080"]
      interval: 30s
      timeout: 20s
      retries: 3
    volumes:
      - '${PWD}/.env:/project/.env'
      - '${PWD}/logs:/project/logs'
      - '${PWD}/config:/project/config'
    networks:
      - services_data_access_network

networks:
  services_data_access_network:
    name: services_data_access_network
    external: true
