version: '3.8'

services:
  main-app:
   depends_on:
    - redis
    - minio
#   restart: always
   image: b0pof/bizon-main
   env_file:
      - '.env'
   environment:
     - CONFIG_PATH=./config/prod.yaml
   ports:
     - '8080:8080'
   healthcheck:
     test: timeout 20s bash -c ':> /dev/tcp/127.0.0.1/8080' || exit 1
     interval: 30s
     timeout: 20s
     retries: 3
   volumes:
     - '${PWD}/logs:/project/logs'
     - '${PWD}/config:/project/config'
  redis:
    image: 'redis'
    restart: always
    ports:
      - '6379:6379'
    healthcheck:
      test: timeout 20s bash -c ':> /dev/tcp/127.0.0.1/6379' || exit 1
      interval: 30s
      timeout: 20s
      retries: 3
    volumes:
      - '${PWD}/redis_data:/data'
  minio:
    image: minio/minio:RELEASE.2024-01-18T22-51-28Z-cpuv1
    volumes:
      - ./minio-data:/data
    ports:
      - '9000:9000'
    environment:
      MINIO_ROOT_USER: ${MINIO_USER}
      MINIO_ROOT_PASSWORD: ${MINIO_PASSWORD}
    command: minio server /data/
    healthcheck:
      test: timeout 20s bash -c ':> /dev/tcp/127.0.0.1/9000' || exit 1
      interval: 30s
      timeout: 20s
      retries: 3
