version: '3.8'

services:
  bizon-auth:
    image: b0pof/bizon-auth
    environment:
      - CONFIG_PATH=./config/prod.yaml
    ports:
      - '9091:9091'
      - '8081:8081'
    healthcheck:
      test: [ "CMD", "bash", "-c", "echo -n '' > /dev/tcp/127.0.0.1/9091" ]
      interval: 30s
      timeout: 20s
      retries: 3
    volumes:
      - '${PWD}/.env:/project/.env'
      - '${PWD}/logs:/project/logs'
      - '${PWD}/config:/project/config'
    networks:
      - services_data_access_network
  bizon-profile:
    image: b0pof/bizon-profile
    environment:
      - CONFIG_PATH=./config/prod.yaml
    ports:
      - '9092:9092'
      - '8082:8082'
    healthcheck:
      test: [ "CMD", "bash", "-c", "echo -n '' > /dev/tcp/127.0.0.1/9092" ]
      interval: 30s
      timeout: 20s
      retries: 3
    volumes:
      - '${PWD}/.env:/project/.env'
      - '${PWD}/logs:/project/logs'
      - '${PWD}/config:/project/config'
    networks:
      - services_data_access_network
  bizon-csat:
    image: b0pof/bizon-csat
    environment:
     - CONFIG_PATH=./config/prod.yaml
    ports:
     - '9093:9093'
     - '8083:8083'
    healthcheck:
      test: [ "CMD", "bash", "-c", "echo -n '' > /dev/tcp/127.0.0.1/9093" ]
      interval: 30s
      timeout: 20s
      retries: 3
    volumes:
     - '${PWD}/.env:/project/.env'
     - '${PWD}/logs:/project/logs'
     - '${PWD}/config:/project/config'
    networks:
     - services_data_access_network
  bizon-review:
    image: b0pof/bizon-review
    environment:
      - CONFIG_PATH=./config/prod.yaml
    ports:
     - '9094:9094'
     - '8084:8084'
    healthcheck:
      test: [ "CMD", "bash", "-c", "echo -n '' > /dev/tcp/127.0.0.1/9094" ]
      interval: 30s
      timeout: 20s
      retries: 3
    volumes:
      - '${PWD}/.env:/project/.env'
      - '${PWD}/logs:/project/logs'
      - '${PWD}/config:/project/config'
    networks:
      - services_data_access_network
  bizon-promotion:
    image: b0pof/bizon-promotion
    environment:
      - CONFIG_PATH=./config/prod.yaml
    ports:
     - '9095:9095'
     - '8085:8085'
    healthcheck:
      test: [ "CMD", "bash", "-c", "echo -n '' > /dev/tcp/127.0.0.1/9095" ]
      interval: 30s
      timeout: 20s
      retries: 3
    volumes:
      - '${PWD}/.env:/project/.env'
      - '${PWD}/logs:/project/logs'
      - '${PWD}/config:/project/config'
    networks:
      - services_data_access_network
  bizon-main:
    image: b0pof/bizon-main
    depends_on:
      - bizon-auth
      - bizon-profile
      - bizon-csat
    environment:
      - CONFIG_PATH=./config/prod.yaml
    ports:
      - '8080:8080'
    healthcheck:
      test: [ "CMD", "bash", "-c", "echo -n '' > /dev/tcp/127.0.0.1/8080" ]
      interval: 30s
      timeout: 20s
      retries: 3
    volumes:
      - '${PWD}/.env:/project/.env'
      - '${PWD}/logs:/project/logs'
      - '${PWD}/config:/project/config'
    networks:
      - services_data_access_network

networks:
  services_data_access_network:
    name: services_data_access_network
    external: true
