version: '3.8'

services:
  main-app:
   depends_on:
    - redis
    - minio
    - postgres
  #  restart: always
   image: b0pof/bizon-main
   env_file:
      - '.env'
   environment:
     - CONFIG_PATH=./config/prod.yaml
   ports:
     - '8080:8080'
   healthcheck:
     test: ["CMD", "bash", "-c", "echo -n '' > /dev/tcp/127.0.0.1/8080"]
     interval: 30s
     timeout: 20s
     retries: 3
   volumes:
     - '${PWD}/logs:/project/logs'
     - '${PWD}/config:/project/config'
  redis:
    image: 'redis'
    restart: always
    ports:
      - '6379:6379'
    healthcheck:
      test: ["CMD", "bash", "-c", "echo -n '' > /dev/tcp/127.0.0.1/6379"]
      interval: 30s
      timeout: 20s
      retries: 3
    volumes:
      - 'redis-data:/data'
  minio:
    image: minio/minio:RELEASE.2024-01-18T22-51-28Z-cpuv1
    volumes:
      - 'minio-data:/data'
    ports:
      - '9000:9000'
    environment:
      MINIO_ROOT_USER: ${MINIO_USER}
      MINIO_ROOT_PASSWORD: ${MINIO_PASSWORD}
    command: minio server /data/
    healthcheck:
      test: ["CMD", "bash", "-c", "echo -n '' > /dev/tcp/127.0.0.1/9000"]
      interval: 30s
      timeout: 20s
      retries: 3
  postgres:
    image: postgres
    volumes:
      - 'postgres-data:/var/lib/postgresql/data'
    ports:
      - '5432:5432'
    user: ${POSTGRES_USER}
    environment:
      - POSTGRES_DB=ozon
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
    healthcheck:
      test: pg_isready
      interval: 10s
      timeout: 10s
      retries: 3
volumes:
  redis-data:
  minio-data:
  postgres-data:
