version: '3.8'

services:
  main-app:
    restart: always
    image: b0pof/bizon-main
    environment:
      - CONFIG_PATH=./config/prod.yaml
    ports:
      - '8080:8080'
    volumes:
      - "${PWD}/logs:/project/logs"
      - "${PWD}/config:/project/config"
