version: '3.8'

services:
  redis:
    image: 'redis'
    container_name: redis
    restart: always
    ports:
      - '6379:6379'
    healthcheck:
      test: ["CMD", "bash", "-c", "echo -n '' > /dev/tcp/127.0.0.1/6379"]
      interval: 30s
      timeout: 20s
      retries: 3
    volumes:
      - 'redis-data:/data'
  minio:
    image: minio/minio:RELEASE.2024-01-18T22-51-28Z-cpuv1
    container_name: minio
    volumes:
      - 'minio-data:/data'
    ports:
      - '9000:9000'
      - '9001:9001'
    environment:
      MINIO_ROOT_USER: FullFocus
      MINIO_ROOT_PASSWORD: FullFocus4
    command: server --console-address :9001 /data
    healthcheck:
      test: ["CMD", "bash", "-c", "echo -n '' > /dev/tcp/127.0.0.1/9000"]
      interval: 30s
      timeout: 20s
      retries: 3
  postgres-main:
    image: postgres:16
    container_name: postgres-main
    volumes:
      - 'postgres-data:/var/lib/postgresql/data'
    ports:
      - '5432:5432'
    user: postgres
    environment:
      - POSTGRES_DB=ozon
      - POSTGRES_PASSWORD=postgres
    healthcheck:
      test: pg_isready
      interval: 10s
      timeout: 10s
      retries: 3
  # postgres-csat:
  #   image: postgres:16
  #   container_name: postgres-csat
  #   volumes:
  #     - 'postgres-data-csat:/var/lib/postgresql/data'
  #   ports:
  #     - '5433:5432'
  #   user: postgres
  #   environment:
  #     - POSTGRES_DB=ozon
  #     - POSTGRES_PASSWORD=postgres
  #   healthcheck:
  #     test: pg_isready
  #     interval: 10s
  #     timeout: 10s
  #     retries: 3
  elasticsearch:
    image: bitnami/elasticsearch:7.17.20-debian-12-r2
    container_name: elasticsearch
    restart: always
    environment:
      node.name: 'es01'
      bootstrap.memory_lock: true
      ES_JAVA_OPTS: '-Xms750m -Xmx750m'
      ELASTIC_USERNAME: elastic
      ELASTIC_PASSWORD: elastic
    ports:
      - '9200:9200'
    volumes:
      - 'elastic-data:/usr/share/elasticsearch/data'
      - '/etc/elasticsearch/config/elasticsearch.yml:/usr/share/elasticsearch/config/elasticsearch.yml'
      - '/etc/elasticsearch/plugins:/usr/share/elasticsearch/plugins'
volumes:
  redis-data:
  minio-data:
  postgres-data:
  postgres-data-csat:
  elastic-data:
