version: '3.8'

services:
  redis:
    image: 'redis'
    container_name: redis
    restart: always
    ports:
      - '6379:6379'
    healthcheck:
      test: ["CMD", "bash", "-c", "echo -n '' > /dev/tcp/127.0.0.1/6379"]
      interval: 30s
      timeout: 20s
      retries: 3
    volumes:
      - 'redis-data:/data'
    networks:
      - services_data_access_network
  minio:
    image: minio/minio:RELEASE.2024-01-18T22-51-28Z-cpuv1
    container_name: minio
    volumes:
      - 'minio-data:/data'
    ports:
      - '9000:9000'
      - '9001:9001'
    environment:
      MINIO_ROOT_USER: FullFocus
      MINIO_ROOT_PASSWORD: FullFocus4
    command: server --console-address :9001 /data
    healthcheck:
      test: ["CMD", "bash", "-c", "echo -n '' > /dev/tcp/127.0.0.1/9000"]
      interval: 30s
      timeout: 20s
      retries: 3
    networks:
      - services_data_access_network
  postgres-main:
    image: postgres:16
    container_name: postgres-main
    volumes:
      - 'postgres-data:/var/lib/postgresql/data'
    ports:
      - '5432:5432'
    user: postgres
    environment:
      - POSTGRES_DB=ozon
      - POSTGRES_PASSWORD=postgres
    healthcheck:
      test: pg_isready
      interval: 10s
      timeout: 10s
      retries: 3
    networks:
      - services_data_access_network
  postgres-csat:
    image: postgres:16
    container_name: postgres-csat
    volumes:
     - 'postgres-data-csat:/var/lib/postgresql/data'
    ports:
     - '5433:5432'
    user: postgres
    environment:
     - POSTGRES_DB=csat
     - POSTGRES_PASSWORD=postgres
    healthcheck:
     test: pg_isready
     interval: 10s
     timeout: 10s
     retries: 3
    networks:
     - services_data_access_network
  elasticsearch:
    container_name: elasticsearch
    image: bitnami/elasticsearch:7.17.20-debian-12-r2
    restart: always
    environment:
      node.name: 'es01'
      bootstrap.memory_lock: true
      ES_JAVA_OPTS: '-Xms750m -Xmx750m'
      ELASTIC_USERNAME: elastic
      ELASTIC_PASSWORD: elastic
    ports:
      - '9200:9200'
    volumes:
      - 'elastic-data:/usr/share/elasticsearch/data'
      - '/etc/elasticsearch/config/elasticsearch.yml:/usr/share/elasticsearch/config/elasticsearch.yml'
      - '/etc/elasticsearch/plugins:/usr/share/elasticsearch/plugins'
    networks:
      - services_data_access_network

  # Monitoring
  prometheus:
    image: prom/prometheus
    container_name: prometheus
    user: root
    env_file:
      - '.env'
    ports:
      - '9090:9090'
    volumes:
      - ./prometheus/:/etc/prometheus/
      - prometheus-data:/prometheus
    command:
      - --config.file=/etc/prometheus/prometheus.yaml
    hostname: prometheus
    environment:
      TZ: "Europe/Moscow"
    networks:
      - services_data_access_network
  grafana:
    image: grafana/grafana:latest
    container_name: grafana
    user: root
    env_file:
      - '.env'
    depends_on:
      - prometheus
    ports:
      - '3100:3000'
    volumes:
      - grafana-data:/var/lib/grafana
    hostname: grafana
    environment:
      - TERM=linux
      - GF_LOG_LEVEL=debug
      - GF_DATAPROXY_LOGGING=true
      - GF_DEFAULT_APP_MODE=development
      - TZ="Europe/Moscow"
    networks:
      - services_data_access_network
  node-exporter:
    image: prom/node-exporter
    container_name: exporter
    volumes:
      - /proc:/host/proc:ro
      - /sys:/host/sys:ro
      - /:/rootfs:ro
    hostname: exporter
    command:
      - --path.procfs=/host/proc
      - --path.sysfs=/host/sys
      - --collector.filesystem.ignored-mount-points
      - ^/(sys|proc|dev|host|etc|rootfs/var/lib/docker/containers|rootfs/var/lib/docker/overlay2|rootfs/run/docker/netns|rootfs/var/lib/docker/aufs)($$|/)
    ports:
      - '9100:9100'
    restart: unless-stopped
    environment:
      TZ: "Europe/Moscow"
    networks:
      - services_data_access_network

  # WS
  centrifugo:
    container_name: centrifugo
    image: centrifugo/centrifugo:v5
    volumes:
      - ./centrifugo/config.json:/centrifugo/config.json
    command: centrifugo -c config.json --port=8000 --admin
    ports:
      - '8000:8000'
    networks:
      - services_data_access_network

  # Logs
  mongodb:
    image: "mongo:5.0"
    volumes:
      - "mongodb_data:/data/db"
    restart: "on-failure"

  opensearch:
    image: "opensearchproject/opensearch:2.4.0"
    environment:
      - "OPENSEARCH_JAVA_OPTS=-Xms1g -Xmx1g"
      - "bootstrap.memory_lock=true"
      - "discovery.type=single-node"
      - "action.auto_create_index=false"
      - "plugins.security.ssl.http.enabled=false"
      - "plugins.security.disabled=true"
    ulimits:
      memlock:
        hard: -1
        soft: -1
      nofile:
        soft: 65536
        hard: 65536
    volumes:
      - "os_data:/usr/share/opensearch/data"
    restart: "on-failure"

  graylog:
    hostname: "server"
    image: "graylog/graylog:5.2.6"
    depends_on:
      opensearch:
        condition: "service_started"
      mongodb:
        condition: "service_started"
    entrypoint: "/usr/bin/tini -- wait-for-it opensearch:9200 --  /docker-entrypoint.sh"
    environment:
      GRAYLOG_NODE_ID_FILE: "/usr/share/graylog/data/config/node-id"
      GRAYLOG_PASSWORD_SECRET: "6QwoZahGXYFDGAMVlmct7vGvo5vTxD8TVhBbsQrI9THl5sdHvNH7XqrGpHVCif9O2N509pHXqTF0ppAWcKu7hoty8JE45BOT"
      GRAYLOG_ROOT_PASSWORD_SHA2: "33c5ebbb01d608c254b3b12413bdb03e46c12797e591770ccf20f5e2819929b2"
      GRAYLOG_HTTP_BIND_ADDRESS: "0.0.0.0:9002"
      GRAYLOG_HTTP_EXTERNAL_URI: "http://localhost:9002/"
      GRAYLOG_ELASTICSEARCH_HOSTS: "http://opensearch:9200"
      GRAYLOG_MONGODB_URI: "mongodb://mongodb:27017/graylog"
    ports:
      - "5044:5044/tcp"   # Beats
      - "5140:5140/udp"   # Syslog
      - "5140:5140/tcp"   # Syslog
      - "5555:5555/tcp"   # RAW TCP
      - "5555:5555/udp"   # RAW TCP
      - "9002:9002/tcp"   # Server API
      - "12201:12201/tcp" # GELF TCP
      - "12201:12201/udp" # GELF UDP
      - "13301:13301/tcp" # Forwarder data
      - "13302:13302/tcp" # Forwarder config
    volumes:
      - "graylog_data:/usr/share/graylog/data/data"
      - "graylog_journal:/usr/share/graylog/data/journal"
    restart: "on-failure"

volumes:
  redis-data:
  minio-data:
  postgres-data:
  postgres-data-csat:
  elastic-data:
  grafana-data:
  prometheus-data:
  mongodb_data:
  os_data:
  graylog_data:
  graylog_journal:
networks:
  services_data_access_network:
    name: services_data_access_network
    external: true
  graylog_network:
    driver: bridge
