global:
  scrape_interval:     10s
  evaluation_interval: 10s

scrape_configs:
  - job_name: "prometheus"
    static_configs:
      - targets: [ 'localhost:9090' ]

  - job_name: "system"
    static_configs:
      - targets: [ 'node-exporter:9100' ]

  - job_name: "main"
    metrics_path: /public/metrics
    static_configs:
      - targets: [ 'bizon-main:8080' ]

  - job_name: "auth"
    metrics_path: /metrics
    static_configs:
      - targets: [ 'bizon-auth:8081' ]

  - job_name: "profile"
    metrics_path: /metrics
    static_configs:
      - targets: [ 'bizon-profile:8082' ]

  - job_name: "csat"
    metrics_path: /metrics
    static_configs:
      - targets: [ 'bizon-csat:8083' ]

  - job_name: "review"
    metrics_path: /metrics
    static_configs:
      - targets: [ 'bizon-review:8084' ]
