global:
  scrape_interval:     10s
  evaluation_interval: 10s

scrape_configs:
  - job_name: "prometheus"
    static_configs:
      - targets: ['localhost:9090']

  - job_name: "exporter"
    metrics_path: /metrics
    static_configs:
      - targets: [ 'node-exporter:9100' ]

  - job_name: "main"
    metrics_path: /api/metrics
    static_configs:
      - targets: [ 'bizon-main:8080' ]

  - job_name: "auth"
    metrics_path: /api/metrics
    static_configs:
      - targets: [ 'bizon-auth:9091' ]

  - job_name: "profile"
    metrics_path: /api/metrics
    static_configs:
      - targets: [ 'bizon-main:9092' ]

  - job_name: "csat"
    metrics_path: /api/metrics
    static_configs:
      - targets: [ 'bizon-main:9093' ]

  - job_name: "review"
    metrics_path: /api/metrics
    static_configs:
      - targets: [ 'bizon-main:9094' ]
