env: "local"
session_ttl: 1h
server:
  port: ":8080"
  timeout: 10s
  idle_timeout: 60s
redis:
  addr: "localhost:6379"
minio:
  addr: "localhost:9000"
  minio_user: ${MINIO_USER}
  minio_password: ${MINIO_PASSWORD}
  minio_access_key: ${MINIO_ACCESS_KEY}
  minio_secret_key: ${MINIO_SECRET_KEY}
  avatar_bucket: "avatars"
postgres_main:
  host: "localhost"
  port: "5432"
  user: ${POSTGRES_USER}
  password: ${POSTGRES_PASSWORD}
  database: "ozon"
  sslmode: "disable"
  search_path: "ozon"
  max_open_conns: 10
  max_idle_time: 10
postgres_csat:
  host: "localhost"
  port: "5433"
  user: ${POSTGRES_USER}
  password: ${POSTGRES_PASSWORD}
  database: "csat"
  sslmode: "disable"
  search_path: "csat"
  max_open_conns: 10
  max_idle_time: 10
elasticsearch:
  host: "localhost"
  port: "9200"
  user: elastic
  password: elastic
