env: "local"
session_ttl: 1h
server:
  port: ":8080"
  timeout: 10s
  idle_timeout: 60s
postgres:
  host: "localhost"
  port: "5432"
  user: "postgres"
  password: "postgres"
  database: "ozon"
  sslmode: "disabled"
