env: "prod"
session_ttl: 24h
server:
  port: ":8080"
  timeout: 5s
  idle_timeout: 60s
redis:
  addr: "redis:6379"
minio:
  addr: "minio:9000"
  minio_user: ${MINIO_USER}
  minio_password: ${MINIO_PASSWORD}
  minio_access_key: ${MINIO_ACCESS_KEY}
  minio_secret_key: ${MINIO_SECRET_KEY}
  avatar_bucket: "avatars"
postgres:
  host: "postgres"
  port: "5432"
  user: ${POSTGRES_USER}
  password: ${POSTGRES_PASSWORD}
  database: "ozon"
  sslmode: "disable"
  search_path: "ozon"
  max_open_conns: 10
  max_idle_time: 10
elasticsearch:
  host: "localhost"
  port: "9200"
  user: ${ELASTIC_USER}
  password: ${ELASTIC_PASSWORD}
