name: Deploy

on:
  push:
    branches: [deploy-setting]
  pull_request:
    branches: [deploy-setting]

jobs:
  build-test: #test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Setup Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.22.x'
      - name: Install dependencies
        run: go mod download
      - name: Run tests
        run: make build #make test
  build:
    runs-on: ubuntu-latest
    needs: build-test
    steps:
      - uses: actions/checkout@v4
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Build image
        run: docker build -t b0pof/bizon-main .
      - name: Push the image
        run: docker push b0pof/bizon-main
  deploy:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Pull the image
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          password: ${{ secrets.PASSWORD }}
          script: |
            cd ~/ozon_project/backend/2024_1_FullFocus
            sudo docker compose down
            sudo docker compose pull
            sudo docker compose up --force-recreate --build -d
            sudo docker image prune -f
